agent:
  topology:
    probes:
      - ovsdb
      - docker
      - runc
      - neutron

  runc:
    run_path:
    - /var/run/runc
    - /var/run/runc-ctrs

analyzer:
  listen: 0.0.0.0:8082
  topology:
      probes:
        - k8s
        - ovn
      ovn:
        address: tcp:100.18.35.73:6641
